USE [master]
GO

CREATE DATABASE [BIKSPR]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BIKSPR', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\BIKSPR.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BIKSPR_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\BIKSPR.ldf' , SIZE = 3456KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BIKSPR] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BIKSPR].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BIKSPR] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [BIKSPR] SET ANSI_NULLS ON 
GO

ALTER DATABASE [BIKSPR] SET ANSI_PADDING ON 
GO

ALTER DATABASE [BIKSPR] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [BIKSPR] SET ARITHABORT ON 
GO

ALTER DATABASE [BIKSPR] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BIKSPR] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [BIKSPR] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BIKSPR] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BIKSPR] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BIKSPR] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [BIKSPR] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [BIKSPR] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BIKSPR] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [BIKSPR] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BIKSPR] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BIKSPR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BIKSPR] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BIKSPR] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BIKSPR] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BIKSPR] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BIKSPR] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BIKSPR] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BIKSPR] SET RECOVERY FULL 
GO

ALTER DATABASE [BIKSPR] SET  MULTI_USER 
GO

ALTER DATABASE [BIKSPR] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BIKSPR] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BIKSPR] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BIKSPR] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BIKSPR] SET  READ_WRITE 
GO


